import type { AuditEvent } from '@/features/audit/types';
import type { Customer } from '@/features/customers/types';
import type { UserProfile } from '@/types/auth';

/**
 * Fictional data for the UI demo. Every record here is invented.
 */
const DEMO_EPOCH = new Date('2026-08-01T04:30:00.000Z');

function stamp(offsetDays: number): Date {
  return new Date(DEMO_EPOCH.getTime() + offsetDays * 24 * 60 * 60 * 1000);
}

export const DEMO_OWNER_UID = 'demo-owner';

/** The profile the demo session signs in as: a full-access owner. */
export const DEMO_OWNER_PROFILE: UserProfile = {
  id: DEMO_OWNER_UID,
  name: 'Demo Owner',
  email: 'demo@devasriya.local',
  mobile: '9000000001',
  designation: 'owner',
  department: 'management',
  role: 'owner',
  isActive: true,
  createdAt: DEMO_EPOCH,
  createdBy: DEMO_OWNER_UID,
  updatedAt: DEMO_EPOCH,
  updatedBy: DEMO_OWNER_UID,
};

export const DEMO_EMPLOYEES: UserProfile[] = [
  DEMO_OWNER_PROFILE,
  {
    id: 'demo-sales',
    name: 'Anita Verma',
    email: 'anita.demo@devasriya.local',
    mobile: '9000000002',
    designation: 'sales-executive',
    department: 'sales',
    role: 'sales',
    isActive: true,
    createdAt: stamp(1),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(1),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-designer',
    name: 'Imran Sheikh',
    email: 'imran.demo@devasriya.local',
    mobile: '9000000003',
    designation: 'graphic-designer',
    department: 'design',
    role: 'designer',
    isActive: true,
    createdAt: stamp(2),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(2),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-production',
    name: 'Sunil Yadav',
    email: 'sunil.demo@devasriya.local',
    mobile: '9000000004',
    designation: 'machine-operator',
    department: 'printing',
    role: 'production',
    isActive: true,
    createdAt: stamp(3),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(3),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-accounts',
    name: 'Priya Nair',
    email: 'priya.demo@devasriya.local',
    mobile: '9000000005',
    designation: 'accountant',
    department: 'accounts',
    role: 'accounts',
    isActive: false,
    createdAt: stamp(4),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(9),
    updatedBy: DEMO_OWNER_UID,
  },
];

export const DEMO_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'demo-audit-1',
    action: 'status-changed',
    targetUserId: 'demo-accounts',
    targetName: 'Priya Nair',
    actorId: DEMO_OWNER_UID,
    actorName: 'Demo Owner',
    before: 'Active',
    after: 'Inactive',
    createdAt: stamp(9),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(9),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-audit-2',
    action: 'employee-created',
    targetUserId: 'demo-accounts',
    targetName: 'Priya Nair',
    actorId: DEMO_OWNER_UID,
    actorName: 'Demo Owner',
    before: '',
    after: 'Accounts, active',
    createdAt: stamp(4),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(4),
    updatedBy: DEMO_OWNER_UID,
  },
];

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'demo-customer-1',
    name: 'Ravi Kumar',
    nameLower: 'ravi kumar',
    type: 'individual',
    mobile: '9812300011',
    alternateMobile: '9812300012',
    email: 'ravi.kumar@example.com',
    address: '12 Station Road, near Bus Stand',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302001',
    preferredLanguage: 'hi',
    notes: 'Regular wedding card orders.',
    isArchived: false,
    portalUserId: null,
    createdAt: stamp(1),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(6),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-customer-2',
    name: 'Shreeji Traders',
    nameLower: 'shreeji traders',
    businessName: 'Shreeji Traders Pvt Ltd',
    type: 'business',
    mobile: '9829100022',
    email: 'accounts@shreejitraders.example',
    address: '4 Market Road, Shop 18',
    city: 'Udaipur',
    state: 'Rajasthan',
    pincode: '313001',
    gstin: '08AABCU9603R1ZM',
    preferredLanguage: 'en',
    notes: 'Monthly flex banners and hoardings. Invoice by email.',
    isArchived: false,
    portalUserId: null,
    createdAt: stamp(2),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(8),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-customer-3',
    name: 'Meena Sharma',
    nameLower: 'meena sharma',
    type: 'individual',
    mobile: '9887200033',
    address: '221 Civil Lines',
    city: 'Ajmer',
    state: 'Rajasthan',
    pincode: '305001',
    preferredLanguage: 'hi',
    isArchived: false,
    portalUserId: null,
    createdAt: stamp(3),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(3),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-customer-4',
    name: 'Gupta Sweets',
    nameLower: 'gupta sweets',
    businessName: 'Gupta Sweets & Namkeen',
    type: 'business',
    mobile: '9414300044',
    alternateMobile: '9414300045',
    email: 'orders@guptasweets.example',
    address: '9 Sardar Patel Marg',
    city: 'Jodhpur',
    state: 'Rajasthan',
    pincode: '342001',
    gstin: '08AACCG1234M1Z7',
    preferredLanguage: 'hi',
    notes: 'Festival packaging labels, seasonal rush in October.',
    isArchived: false,
    portalUserId: null,
    createdAt: stamp(4),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(10),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-customer-5',
    name: 'Bharat Coaching Classes',
    nameLower: 'bharat coaching classes',
    businessName: 'Bharat Coaching Classes',
    type: 'business',
    mobile: '9950400055',
    email: 'info@bharatcoaching.example',
    address: '3rd Floor, Ganpati Plaza',
    city: 'Kota',
    state: 'Rajasthan',
    pincode: '324001',
    preferredLanguage: 'en',
    notes: 'Admission season posters and standees.',
    isArchived: false,
    portalUserId: null,
    createdAt: stamp(5),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(5),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-customer-6',
    name: 'Old Signage Works',
    nameLower: 'old signage works',
    businessName: 'Old Signage Works',
    type: 'business',
    mobile: '9660500066',
    address: '7 Industrial Area, Phase 2',
    city: 'Bhilwara',
    state: 'Rajasthan',
    pincode: '311001',
    preferredLanguage: 'hi',
    notes: 'Shifted city. Kept for old records.',
    isArchived: true,
    portalUserId: null,
    createdAt: stamp(1),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(12),
    updatedBy: DEMO_OWNER_UID,
  },
];
