import type { AuditEvent } from '@/features/audit/types';
import type { Customer } from '@/features/customers/types';
import type { Enquiry } from '@/features/enquiries/types';
import type { Job } from '@/features/jobs/types';
import type { Location } from '@/features/locations/types';
import type { UserProfile } from '@/types/auth';

/**
 * Fictional data for the UI demo. Every record here is invented.
 */
const DEMO_EPOCH = new Date('2026-08-01T04:30:00.000Z');

function stamp(offsetDays: number): Date {
  return new Date(DEMO_EPOCH.getTime() + offsetDays * 24 * 60 * 60 * 1000);
}

export const DEMO_OWNER_UID = 'demo-owner';

/** The profile the demo session signs in as: a full-access owner. */
export const DEMO_OWNER_PROFILE: UserProfile = {
  id: DEMO_OWNER_UID,
  name: 'Demo Owner',
  email: 'demo@devasriya.local',
  mobile: '9000000001',
  designation: 'owner',
  department: 'management',
  role: 'owner',
  isActive: true,
  createdAt: DEMO_EPOCH,
  createdBy: DEMO_OWNER_UID,
  updatedAt: DEMO_EPOCH,
  updatedBy: DEMO_OWNER_UID,
};

export const DEMO_EMPLOYEES: UserProfile[] = [
  DEMO_OWNER_PROFILE,
  {
    id: 'demo-sales',
    name: 'Anita Verma',
    email: 'anita.demo@devasriya.local',
    mobile: '9000000002',
    designation: 'sales-executive',
    department: 'sales',
    role: 'sales',
    isActive: true,
    createdAt: stamp(1),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(1),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-designer',
    name: 'Imran Sheikh',
    email: 'imran.demo@devasriya.local',
    mobile: '9000000003',
    designation: 'graphic-designer',
    department: 'design',
    role: 'designer',
    isActive: true,
    createdAt: stamp(2),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(2),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-production',
    name: 'Sunil Yadav',
    email: 'sunil.demo@devasriya.local',
    mobile: '9000000004',
    designation: 'machine-operator',
    department: 'printing',
    role: 'production',
    isActive: true,
    createdAt: stamp(3),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(3),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-accounts',
    name: 'Priya Nair',
    email: 'priya.demo@devasriya.local',
    mobile: '9000000005',
    designation: 'accountant',
    department: 'accounts',
    role: 'accounts',
    isActive: false,
    createdAt: stamp(4),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(9),
    updatedBy: DEMO_OWNER_UID,
  },
];

export const DEMO_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'demo-audit-1',
    action: 'status-changed',
    targetUserId: 'demo-accounts',
    targetName: 'Priya Nair',
    actorId: DEMO_OWNER_UID,
    actorName: 'Demo Owner',
    before: 'Active',
    after: 'Inactive',
    createdAt: stamp(9),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(9),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-audit-2',
    action: 'employee-created',
    targetUserId: 'demo-accounts',
    targetName: 'Priya Nair',
    actorId: DEMO_OWNER_UID,
    actorName: 'Demo Owner',
    before: '',
    after: 'Accounts, active',
    createdAt: stamp(4),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(4),
    updatedBy: DEMO_OWNER_UID,
  },
];

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'demo-customer-1',
    name: 'Ravi Kumar',
    nameLower: 'ravi kumar',
    type: 'individual',
    mobile: '9812300011',
    alternateMobile: '9812300012',
    email: 'ravi.kumar@example.com',
    address: '12 Station Road, near Bus Stand',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302001',
    preferredLanguage: 'hi',
    notes: 'Regular wedding card orders.',
    isArchived: false,
    portalUserId: null,
    createdAt: stamp(1),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(6),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-customer-2',
    name: 'Shreeji Traders',
    nameLower: 'shreeji traders',
    businessName: 'Shreeji Traders Pvt Ltd',
    type: 'business',
    mobile: '9829100022',
    email: 'accounts@shreejitraders.example',
    address: '4 Market Road, Shop 18',
    city: 'Udaipur',
    state: 'Rajasthan',
    pincode: '313001',
    gstin: '08AABCU9603R1ZM',
    preferredLanguage: 'en',
    notes: 'Monthly flex banners and hoardings. Invoice by email.',
    isArchived: false,
    portalUserId: null,
    createdAt: stamp(2),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(8),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-customer-3',
    name: 'Meena Sharma',
    nameLower: 'meena sharma',
    type: 'individual',
    mobile: '9887200033',
    address: '221 Civil Lines',
    city: 'Ajmer',
    state: 'Rajasthan',
    pincode: '305001',
    preferredLanguage: 'hi',
    isArchived: false,
    portalUserId: null,
    createdAt: stamp(3),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(3),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-customer-4',
    name: 'Gupta Sweets',
    nameLower: 'gupta sweets',
    businessName: 'Gupta Sweets & Namkeen',
    type: 'business',
    mobile: '9414300044',
    alternateMobile: '9414300045',
    email: 'orders@guptasweets.example',
    address: '9 Sardar Patel Marg',
    city: 'Jodhpur',
    state: 'Rajasthan',
    pincode: '342001',
    gstin: '08AACCG1234M1Z7',
    preferredLanguage: 'hi',
    notes: 'Festival packaging labels, seasonal rush in October.',
    isArchived: false,
    portalUserId: null,
    createdAt: stamp(4),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(10),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-customer-5',
    name: 'Bharat Coaching Classes',
    nameLower: 'bharat coaching classes',
    businessName: 'Bharat Coaching Classes',
    type: 'business',
    mobile: '9950400055',
    email: 'info@bharatcoaching.example',
    address: '3rd Floor, Ganpati Plaza',
    city: 'Kota',
    state: 'Rajasthan',
    pincode: '324001',
    preferredLanguage: 'en',
    notes: 'Admission season posters and standees.',
    isArchived: false,
    portalUserId: null,
    createdAt: stamp(5),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(5),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-customer-6',
    name: 'Old Signage Works',
    nameLower: 'old signage works',
    businessName: 'Old Signage Works',
    type: 'business',
    mobile: '9660500066',
    address: '7 Industrial Area, Phase 2',
    city: 'Bhilwara',
    state: 'Rajasthan',
    pincode: '311001',
    preferredLanguage: 'hi',
    notes: 'Shifted city. Kept for old records.',
    isArchived: true,
    portalUserId: null,
    createdAt: stamp(1),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(12),
    updatedBy: DEMO_OWNER_UID,
  },
];

// ---------------------------------------------------------------------------
// Module 4 demo data: pickup offices, enquiries and jobs
// ---------------------------------------------------------------------------

export const DEMO_LOCATIONS: Location[] = [
  {
    id: 'demo-location-1',
    name: 'Main Press, Station Road',
    address: '14 Station Road, Jaipur 302001',
    phone: '9000001001',
    contactUserId: null,
    contactName: 'Anita Verma',
    contactMobile: '9000000002',
    isActive: true,
    createdAt: DEMO_EPOCH,
    createdBy: DEMO_OWNER_UID,
    updatedAt: DEMO_EPOCH,
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-location-2',
    name: 'City Branch, Market Road',
    address: '2 Market Road, Udaipur 313001',
    phone: '9000001002',
    contactUserId: null,
    contactName: 'Sunil Yadav',
    contactMobile: '9000000004',
    isActive: true,
    createdAt: DEMO_EPOCH,
    createdBy: DEMO_OWNER_UID,
    updatedAt: DEMO_EPOCH,
    updatedBy: DEMO_OWNER_UID,
  },
];

export const DEMO_ENQUIRIES: Enquiry[] = [
  {
    id: 'demo-enquiry-1',
    enquiryNumber: 'ENQ-2627-0001',
    customerId: 'demo-customer-1',
    customerName: 'Ravi Kumar',
    customerMobile: '9812300011',
    enquiryDate: stamp(6),
    source: 'walk-in',
    requirementText:
      'Wedding cards, 250 pieces, gold foil on maroon paper. Needs a sample before printing.',
    requirementAudio: null,
    notes: 'Budget conscious, asked for two options.',
    assignedToId: 'demo-sales',
    assignedToName: 'Anita Verma',
    nextFollowUpAt: stamp(9),
    followUps: [
      {
        at: stamp(7),
        byId: 'demo-sales',
        byName: 'Anita Verma',
        note: 'Called and shared two paper options. Customer will confirm after the family decides.',
      },
    ],
    status: 'follow-up',
    convertedJobId: null,
    convertedAt: null,
    createdAt: stamp(6),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(7),
    updatedBy: 'demo-sales',
  },
  {
    id: 'demo-enquiry-2',
    enquiryNumber: 'ENQ-2627-0002',
    customerId: 'demo-customer-2',
    customerName: 'Shreeji Traders',
    customerMobile: '9829100022',
    enquiryDate: stamp(8),
    source: 'whatsapp',
    requirementText:
      'Two flex hoardings, 10ft x 6ft, for the Diwali sale. Same design as last year.',
    requirementAudio: null,
    assignedToId: null,
    assignedToName: null,
    nextFollowUpAt: null,
    followUps: [],
    status: 'converted',
    convertedJobId: 'demo-job-1',
    convertedAt: stamp(9),
    createdAt: stamp(8),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(9),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-enquiry-3',
    enquiryNumber: 'ENQ-2627-0003',
    customerId: 'demo-customer-5',
    customerName: 'Bharat Coaching Classes',
    customerMobile: '9950400055',
    enquiryDate: stamp(11),
    source: 'phone',
    requirementText: 'Admission season posters, A2 size, 300 copies, plus 4 standees.',
    requirementAudio: null,
    assignedToId: null,
    assignedToName: null,
    nextFollowUpAt: stamp(13),
    followUps: [],
    status: 'quotation-required',
    convertedJobId: null,
    convertedAt: null,
    createdAt: stamp(11),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(11),
    updatedBy: DEMO_OWNER_UID,
  },
];

export const DEMO_JOBS: Job[] = [
  {
    id: 'demo-job-1',
    jobNumber: 'JOB-2627-0001',
    customerId: 'demo-customer-2',
    customerName: 'Shreeji Traders',
    customerMobile: '9829100022',
    enquiryId: 'demo-enquiry-2',
    enquiryNumber: 'ENQ-2627-0002',
    jobDate: stamp(9),
    title: 'Diwali sale hoardings',
    requirementText:
      'Two flex hoardings, 10ft x 6ft, for the Diwali sale. Same design as last year.',
    requirementAudio: null,
    priority: 'urgent',
    expectedDeliveryDate: stamp(14),
    internalNotes: 'Reuse last year artwork, change dates and offer text.',
    pickupLocationId: 'demo-location-2',
    pickupLocationName: 'City Branch, Market Road',
    contactPersonId: null,
    contactPersonName: 'Sunil Yadav',
    contactPersonMobile: '9000000004',
    assignedToId: 'demo-designer',
    assignedToName: 'Imran Sheikh',
    status: 'in-progress',
    createdAt: stamp(9),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(10),
    updatedBy: DEMO_OWNER_UID,
  },
  {
    id: 'demo-job-2',
    jobNumber: 'JOB-2627-0002',
    customerId: 'demo-customer-4',
    customerName: 'Gupta Sweets',
    customerMobile: '9414300044',
    enquiryId: null,
    enquiryNumber: null,
    jobDate: stamp(12),
    title: 'Festival box labels',
    requirementText: 'Repeat order: 2000 sweet box labels, same artwork as last festival.',
    requirementAudio: null,
    priority: 'normal',
    expectedDeliveryDate: stamp(18),
    pickupLocationId: 'demo-location-1',
    pickupLocationName: 'Main Press, Station Road',
    contactPersonId: null,
    contactPersonName: 'Anita Verma',
    contactPersonMobile: '9000000002',
    assignedToId: null,
    assignedToName: null,
    status: 'open',
    createdAt: stamp(12),
    createdBy: DEMO_OWNER_UID,
    updatedAt: stamp(12),
    updatedBy: DEMO_OWNER_UID,
  },
];
