import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // Edge Functions are Deno, not Node: they resolve `jsr:` and `npm:`
    // specifiers and are type-checked by `supabase functions serve`, not by the
    // application tsconfig.
    ignores: ['dist', 'coverage', 'node_modules', '*.tsbuildinfo', 'supabase/functions/**'],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommendedTypeChecked],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      // The UI layer must never import the Firebase SDK directly - all data
      // access goes through src/services. See docs/ARCHITECTURE.md.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@supabase/supabase-js', '@/lib/supabase/*'],
              message:
                'Do not use the Supabase SDK directly. Go through src/services (data-access layer).',
            },
          ],
        },
      ],
    },
  },
  {
    // The data-access layer is allowed to use the SDK: the Supabase client, the
    // shared row mappers, and the service folder inside each feature. UI code
    // (components, pages, hooks) is not.
    files: [
      'src/lib/supabase/**/*.ts',
      'src/services/**/*.ts',
      'src/features/*/services/**/*.ts',
      'src/test/integration/**/*.ts',
      'src/**/*.integration.test.ts',
    ],
    rules: {
      'no-restricted-imports': 'off',
    },
  },
  {
    // shadcn/ui components are vendored and regenerated by the shadcn CLI; they
    // export variant helpers alongside the component by design.
    files: ['src/components/ui/**/*.tsx'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  {
    files: ['**/*.{test,spec}.{ts,tsx}', 'vitest.setup.ts'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      // Asserting on mocked methods pulled off an object is normal in tests.
      '@typescript-eslint/unbound-method': 'off',
    },
  },
  {
    // Integration tests drive Supabase through the SDK on purpose - they
    // verify the deployed policies, not application behaviour, so they have to
    // reach past the service layer.
    files: ['**/*.integration.test.ts', 'src/test/integration/**/*.ts'],
    rules: {
      'no-restricted-imports': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
    },
  },
  {
    files: ['**/*.js'],
    extends: [tseslint.configs.disableTypeChecked],
  },
  {
    // Node scripts: developer tooling, not part of the browser bundle.
    files: ['scripts/**/*.mjs'],
    extends: [js.configs.recommended, tseslint.configs.disableTypeChecked],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: globals.node,
    },
  },
  prettier,
);
