import { isDemoMode } from '@/config/demo';
import { demoFileUrl, rememberDemoFile } from '@/features/demo/demo-store';
import { getSupabase } from '@/lib/supabase/client';
import { toAppError } from '@/lib/supabase/errors';
import { BUCKETS, SIGNED_URL_TTL_SECONDS } from '@/services/base/tables';
import {
  DESIGN_FILE_EXTENSIONS,
  DESIGN_MIME_TYPES,
  MAX_DESIGN_BYTES,
  isDesignMimeType,
  previewKindFor,
  type DesignAttachment,
  type DesignMimeType,
  type DesignPreview,
} from '@/types/attachments';
import { AppError, type Id } from '@/types/common';

/**
 * Immutable path for one design file.
 *
 * The attachment id is part of the path, so a revision never writes over the
 * file an earlier version points at - which is what makes an approved design a
 * record of what was actually approved. The bucket has no update policy and no
 * delete policy at all, so this is enforced rather than merely intended.
 *
 * The first folder segment is the job id, which is how the storage policy works
 * out whether the customer asking is the customer whose order it is.
 */
export function buildDesignPath(jobId: Id, attachmentId: Id, mimeType: DesignMimeType): string {
  return `${jobId}/${attachmentId}.${DESIGN_FILE_EXTENSIONS[mimeType]}`;
}

export function humanFileSize(bytes: number): string {
  if (bytes < 1024) return `${String(bytes)} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export type DesignFileCheck =
  { ok: true; mimeType: DesignMimeType } | { ok: false; message: string };

/**
 * Checks a chosen file before anything is uploaded.
 *
 * The same limits are set on the bucket, so a client that skips this is refused
 * by Storage; this exists to say why, in words, before the designer is waiting
 * on a failed upload.
 */
export function checkDesignFile(file: { type: string; size: number }): DesignFileCheck {
  if (!isDesignMimeType(file.type)) {
    const accepted = DESIGN_MIME_TYPES.map((type) => DESIGN_FILE_EXTENSIONS[type].toUpperCase());
    return {
      ok: false,
      message: `Designs must be ${accepted.join(', ')}. Send source files another way.`,
    };
  }

  if (file.size > MAX_DESIGN_BYTES) {
    return {
      ok: false,
      message: `That file is ${humanFileSize(file.size)}. The limit is ${humanFileSize(MAX_DESIGN_BYTES)}.`,
    };
  }

  if (file.size === 0) {
    return { ok: false, message: 'That file is empty.' };
  }

  return { ok: true, mimeType: file.type };
}

/** Measures an image so the review screen can reserve the right space. */
export async function measurePreview(file: Blob, mimeType: DesignMimeType): Promise<DesignPreview> {
  const kind = previewKindFor(mimeType);
  if (
    kind !== 'image' ||
    typeof Image === 'undefined' ||
    typeof URL.createObjectURL !== 'function'
  ) {
    return { kind, width: null, height: null };
  }

  const url = URL.createObjectURL(file);
  try {
    return await new Promise<DesignPreview>((resolve) => {
      const image = new Image();
      image.onload = () => {
        resolve({ kind, width: image.naturalWidth || null, height: image.naturalHeight || null });
      };
      image.onerror = () => {
        resolve({ kind, width: null, height: null });
      };
      image.src = url;
    });
  } finally {
    URL.revokeObjectURL(url);
  }
}

export interface UploadDesignFileInput {
  jobId: Id;
  /** Generated by the caller, so the path is known before the row exists. */
  attachmentId: Id;
  file: Blob & { name?: string };
  mimeType: DesignMimeType;
  originalFileName: string;
  uploadedById: Id;
}

/**
 * Uploads one design file and returns the metadata to store on the version.
 *
 * The caller writes the row only after this resolves, so a failed upload never
 * leaves a version pointing at a file that is not there. `upsert` is false and
 * the bucket has no update policy, so a second write to the same path is
 * refused twice over.
 */
export async function uploadDesignFile({
  jobId,
  attachmentId,
  file,
  mimeType,
  originalFileName,
  uploadedById,
}: UploadDesignFileInput): Promise<DesignAttachment> {
  if (file.size > MAX_DESIGN_BYTES) {
    throw new AppError('invalid-input', 'That design file is too large.');
  }

  const attachment: DesignAttachment = {
    id: attachmentId,
    storagePath: buildDesignPath(jobId, attachmentId, mimeType),
    mimeType,
    sizeBytes: file.size,
    originalFileName,
    uploadedAt: new Date(),
    uploadedById,
  };

  if (isDemoMode()) {
    // The demo keeps the blob in the browser; Storage is never contacted.
    if (typeof URL.createObjectURL === 'function') {
      rememberDemoFile(attachmentId, URL.createObjectURL(file));
    }
    return attachment;
  }

  try {
    const { error } = await getSupabase()
      .storage.from(BUCKETS.designs)
      .upload(attachment.storagePath, file, { contentType: mimeType, upsert: false });
    if (error) throw error;
    return attachment;
  } catch (error) {
    throw toAppError(error);
  }
}

/**
 * Resolves a viewable URL for whoever is signed in - staff or customer.
 *
 * Never persisted on the row: a signed URL is a bearer token, and a design is
 * exactly the kind of thing that must not leak to another customer. It is
 * minted when somebody looks at the file and expires shortly afterwards, so it
 * only has to outlive the page that asked for it.
 */
export async function resolveDesignUrl(attachment: DesignAttachment): Promise<string> {
  if (isDemoMode()) {
    const url = demoFileUrl(attachment.id);
    if (!url) throw new AppError('not-found', 'This sample design is not available in the demo.');
    return url;
  }

  try {
    const { data, error } = await getSupabase()
      .storage.from(BUCKETS.designs)
      .createSignedUrl(attachment.storagePath, SIGNED_URL_TTL_SECONDS);
    if (error) throw error;
    return data.signedUrl;
  } catch (error) {
    throw toAppError(error);
  }
}

/**
 * Tidies up a file whose version row then failed to write.
 *
 * The designs bucket has no delete policy, deliberately: a rule that let
 * anybody remove a design object would also let somebody remove the artwork an
 * approved version points at. So this usually leaves an unreferenced object
 * behind, and that is the trade we want - an orphaned file costs storage, a
 * deletable one costs the guarantee that an approval means something.
 */
export async function discardDesignFile(attachment: DesignAttachment): Promise<void> {
  if (isDemoMode()) return;
  try {
    await getSupabase().storage.from(BUCKETS.designs).remove([attachment.storagePath]);
  } catch {
    // Expected: design objects are immutable. Nothing references this one.
  }
}
