-- ---------------------------------------------------------------------------
-- Devasriya Print - the permission matrix, seeded
--
-- Generated from src/features/permissions/matrix.ts, which stays the source of
-- truth for the UI. A test asserts the two copies are identical, so drift is a
-- failing build rather than a security incident.
--
--   owner       31 permissions (everything)
--   admin       29 (everything except the two owner-only permissions)
--   sales       20
--   designer     9   - no estimates:view, so no sight of money
--   production  12   - no estimates:view, so no sight of money
--   accounts     9   - no designs:view
--   viewer       8   - read only
-- ---------------------------------------------------------------------------

delete from public.role_permissions;

insert into public.role_permissions (role, permission) values
  -- owner (31)
  ('owner','dashboard:view'),
  ('owner','customers:view'),
  ('owner','customers:create'),
  ('owner','customers:edit'),
  ('owner','enquiries:view'),
  ('owner','enquiries:create'),
  ('owner','enquiries:edit'),
  ('owner','jobs:view'),
  ('owner','jobs:create'),
  ('owner','jobs:edit'),
  ('owner','jobs:assign'),
  ('owner','estimates:view'),
  ('owner','estimates:create'),
  ('owner','estimates:edit'),
  ('owner','estimates:approve'),
  ('owner','designs:view'),
  ('owner','designs:upload'),
  ('owner','designs:approve'),
  ('owner','production:view'),
  ('owner','production:update'),
  ('owner','employees:view'),
  ('owner','employees:manage'),
  ('owner','employees:manage-admins'),
  ('owner','billing:view'),
  ('owner','billing:create'),
  ('owner','billing:edit'),
  ('owner','inventory:view'),
  ('owner','inventory:manage'),
  ('owner','reports:view'),
  ('owner','settings:view'),
  ('owner','settings:manage'),
  -- admin (29)
  ('admin','dashboard:view'),
  ('admin','customers:view'),
  ('admin','customers:create'),
  ('admin','customers:edit'),
  ('admin','enquiries:view'),
  ('admin','enquiries:create'),
  ('admin','enquiries:edit'),
  ('admin','jobs:view'),
  ('admin','jobs:create'),
  ('admin','jobs:edit'),
  ('admin','jobs:assign'),
  ('admin','estimates:view'),
  ('admin','estimates:create'),
  ('admin','estimates:edit'),
  ('admin','estimates:approve'),
  ('admin','designs:view'),
  ('admin','designs:upload'),
  ('admin','designs:approve'),
  ('admin','production:view'),
  ('admin','production:update'),
  ('admin','employees:view'),
  ('admin','employees:manage'),
  ('admin','billing:view'),
  ('admin','billing:create'),
  ('admin','billing:edit'),
  ('admin','inventory:view'),
  ('admin','inventory:manage'),
  ('admin','reports:view'),
  ('admin','settings:view'),
  -- sales (20)
  ('sales','dashboard:view'),
  ('sales','customers:view'),
  ('sales','customers:create'),
  ('sales','customers:edit'),
  ('sales','enquiries:view'),
  ('sales','enquiries:create'),
  ('sales','enquiries:edit'),
  ('sales','jobs:view'),
  ('sales','jobs:create'),
  ('sales','jobs:edit'),
  ('sales','estimates:view'),
  ('sales','estimates:create'),
  ('sales','estimates:edit'),
  ('sales','estimates:approve'),
  ('sales','designs:view'),
  ('sales','designs:approve'),
  ('sales','production:view'),
  ('sales','billing:view'),
  ('sales','inventory:view'),
  ('sales','reports:view'),
  -- designer (9)
  ('designer','dashboard:view'),
  ('designer','customers:view'),
  ('designer','enquiries:view'),
  ('designer','jobs:view'),
  ('designer','designs:view'),
  ('designer','designs:upload'),
  ('designer','production:view'),
  ('designer','production:update'),
  ('designer','inventory:view'),
  -- production (12)
  ('production','dashboard:view'),
  ('production','customers:view'),
  ('production','enquiries:view'),
  ('production','jobs:view'),
  ('production','jobs:edit'),
  ('production','designs:view'),
  ('production','production:view'),
  ('production','production:update'),
  ('production','employees:view'),
  ('production','inventory:view'),
  ('production','inventory:manage'),
  ('production','reports:view'),
  -- accounts (9)
  ('accounts','dashboard:view'),
  ('accounts','customers:view'),
  ('accounts','jobs:view'),
  ('accounts','estimates:view'),
  ('accounts','billing:view'),
  ('accounts','billing:create'),
  ('accounts','billing:edit'),
  ('accounts','inventory:view'),
  ('accounts','reports:view'),
  -- viewer (8)
  ('viewer','dashboard:view'),
  ('viewer','customers:view'),
  ('viewer','enquiries:view'),
  ('viewer','jobs:view'),
  ('viewer','estimates:view'),
  ('viewer','designs:view'),
  ('viewer','production:view'),
  ('viewer','reports:view');
